### ISSUE TITLE
BETA1のcurlコマンド例のURLが誤っています。

### ISSUE THREAD

**Issue by ytetsuro** [project-tsurugi/tsurugidb#16]
ディレクトリ名に誤りがあるようです。 2 -> 1

https://github.com/project-tsurugi/tsurugidb/releases/tag/1.0.0-BETA1

```diff
- curl -OL https://github.com/project-tsurugi/tsurugidb/releases/download/1.0.0-BETA2/tsurugidb-1.0.0-BETA1.tar.gz
+ curl -OL https://github.com/project-tsurugi/tsurugidb/releases/download/1.0.0-BETA1/tsurugidb-1.0.0-BETA1.tar.gz
```

**Comment by akirakw** [comment]
@ytetsuro レポートして頂いた通り、1.0.0-BETA1のダウンロードURLが誤っていたためリリースページを修正しました。
https://github.com/project-tsurugi/tsurugidb/releases/tag/1.0.0-BETA1

1.0.0-BETA2をリリースした際に1.0.0-BETA1のリリースページも構成を変更したのですが、そのタイミングで誤りが混入してしまったようです。

**Comment by ytetsuro** [comment]
ありがとうございます！

**Comment by akirakw** [comment]
@ytetsuro こちらこそ、レポートありがとうございました！
