### ISSUE TITLE
LTXと条件付きreadにおけるwrite skewについて

### ISSUE THREAD

**Issue by taku0** [project-tsurugi/tsurugidb#5]
LTXはserializableとのことですが、条件付きreadの結果に依存してINSERTをするとwrite skew (という用語でよいのかは自信ありません)が発生するようです。
`SELECT SUM(value) + 1 FROM foo`の結果を`foo`にINSERTする、というのを2つのトランザクションから並行して実施した場合、両方とも成功します。

実行環境:
- Docker版tsurugi:latest (Id: sha256:438aad9c6c49c51c97253dd6e363abc8366ede009b5899ca38975cb36a051365, Created: 2023-10-05T02:34:58.823587414Z)
- tgsql

準備

```sql
CREATE TABLE test (
  id int PRIMARY KEY,
  value int NOT NULL
);

INSERT INTO test (id, value) VALUES (1, 1);

COMMIT;
```

トランザクション1 (途中まで)

```sql
BEGIN LONG TRANSACTION WRITE PRESERVE test;

-- 本来は
-- INSERT INTO test (id, value) VALUES (2, SELECT SUM(value) + 1 FROM test);
-- と書きたいが、まだサポートされていないので、クライアント側でSELECT結果をINSERTに渡しているものとする。

SELECT SUM(value) + 1 FROM test;
INSERT INTO test (id, value) VALUES (2, 2); -- 前のSELECTの結果。
-- まだコミットはしない
```

トランザクション2(途中まで)

```sql
BEGIN LONG TRANSACTION WRITE PRESERVE test;

SELECT SUM(value) + 1 FROM test;
INSERT INTO test (id, value) VALUES (3, 2); -- 前のSELECTの結果。
-- まだコミットはしない
```

トランザクション1

```sql
COMMIT;
```

トランザクション2

```sql
COMMIT;

```

この場合、2つのトランザクションはserializableでないのでどちらかはCOMMITに失敗するはずですが、両方ともコミットに成功します。
なお、トランザクション2を先にCOMMITしようとした場合、トランザクション2がブロックされ、トランザクション1がコミットしたタイミングでトランザクション2が`CC_LTX_PHANTOM_AVOIDANCE`でエラーとなるため問題ありません。
まだ使い方などよく理解しておらず、書き方に問題があればご指摘いただけると助かります。
(あと、Issueは日本語で大丈夫でしょうか)

**Comment by taku0** [comment]
本質的には同じですが、他の例です。

## 例2

準備:
```sql

CREATE TABLE test1 (
  id int PRIMARY KEY,
  value int NOT NULL
);

CREATE TABLE test2 (
  id int PRIMARY KEY,
  value int NOT NULL
);

INSERT INTO test1 (id, value) VALUES (1, 1);
```

トランザクション1

```sql
BEGIN LONG TRANSACTION WRITE PRESERVE test2;

SELECT * FROM test1;
```

トランザクション2
```sql

BEGIN TRANSACTION;

SELECT COUNT(*) FROM test2;
UPDATE test1 SET value = 0; -- 前のSELECTの結果

COMMIT;
```

トランザクション1

```sql
INSERT INTO test2 (id, value) VALUES (1, 1); -- 前のSELECTの結果

COMMIT;
```

## 例3

PostgreSQLのserializable論文の例
https://browse.arxiv.org/pdf/1208.4179.pdf
Figure 2より。

準備:

```sql
CREATE TABLE current_batch (
  id int PRIMARY KEY,
  value int NOT NULL
);

INSERT INTO current_batch (id, value) VALUES (1, 1);

CREATE TABLE receipts (
  id int PRIMARY KEY,
  batch int NOT NULL,
  amount int NOT NULL
);

-- 次の行がある場合はトランザクション2がCOMMIT時にCC_LTX_PHANTOM_AVOIDANCEで止まる。
-- INSERT INTO receipts (id, batch, amount) VALUES (1, 1, 100);

COMMIT;
```

トランザクション2

```sql
-- OCCの場合はCOMMIT時にCC_OCC_READ_VERIFYで止まる。
BEGIN LONG TRANSACTION WRITE PRESERVE receipts;

SELECT * FROM current_batch;
```

トランザクション3

```sql
BEGIN TRANSACTION;

UPDATE current_batch SET value = value + 1;

COMMIT;
```

トランザクション1

```sql
BEGIN LONG TRANSACTION;

SELECT * FROM current_batch;

SELECT
  SUM(amount)
FROM
  receipts
WHERE
  batch = 1; -- 前のSELECTの結果 - 1

COMMIT;
```

トランザクション2

```sql
INSERT INTO receipts (id, batch, amount) VALUES (2, 1, 200);

COMMIT;
```

**Comment by okachimachiorz** [comment]
まずはIssueの登録ありがとうございます。一回、こちらで引き取りますね。
おそらく複数のIssueに分ける必要があるのかなと思っていますので、一旦再現と整理をさせてください。

えっとIssueは日本語でOKです。

当初の予定はgithubは英語で、日本語は書籍の切り分けの予定でしたが、Issueは原則日本語OKにしましょう。
書籍にも「あとはついでに言うと日本語で質問や意見を言ってもまともに相手にしてもらえる」と堂々と書いてますので。

**Comment by taku0** [comment]
確かに、同じ問題(INSERTとSELECTの問題)かと思っていましたが、2番目と3番目の例(空テーブルの時だけ起きる?)は1番目(空でなくても起きる)とは別の原因かもしれません。

**Comment by okachimachiorz** [comment]
@taku0 

時間が開いたので、中間報告です。
Issue対象については、ある程度目処がつきつつあります。
該当bugについては、β2を近々リリースできるので、（今のところは）そこで回収する予定です。
その時分にはご確認の上、Issueのクローズまたは追加のご指摘を頂ければ幸甚です。

以下、内容です。

該当Issueとしては、やはりbugとしては複数のものを内包しています。概ね以下の事象を認識・手当しています。

- 特定のタイミングでopen_scanでのreadの空振りを認識していない（key_read/value_readで行っている）
- open_scanでのreadの空振りをread infoとして登録してない。（結果として空デーブルでのconflictの未回収が起きる）

特定の状況下でのoverwriterの認識の実装でbugがあるので、その対応をしています。
同時に、overwriterの認識のパスの再確認を行っています。
また、当該bug以外の漏れも同時で見つかっており、その対応も一緒に行っている状況です。

このIssueに付随して、CCのテストのタイムスケール（msec）がSQLコンソール・レイヤーからのタイムスケール（sec）に
合っていないとの認識の元、追加的に両者タイトに連結したテスト及び
テスト実装フレームワークを構築・実施する仕組みを導入中です。

**Comment by okachimachiorz** [comment]
@taku0 
β2リリースしました。
https://github.com/project-tsurugi/tsurugidb/releases/tag/1.0.0-BETA2
上記Issueを解決していると思います。
恐れ入りますが、ご確認お願いします。

**Comment by taku0** [comment]
確認しました。どの問題も修正されているようです。

**Comment by okachimachiorz** [comment]
確認ありがとうございます。問題が解決されてるようであればIssueのクローズをお願いします。さらに問題が追加であるようであれば、別にまたIssueをオープンしていただければ助かります。

**Comment by taku0** [comment]
クローズします。
